server:
  port: 8081

 spring:
   cloud:
     config:
       server:
         git:
           uri: https://github.com/todocodeacademy/config-server-test.git
           searchPath: config-data
           username: ${GIT_USER}
           password: ${GIT PASSWORD}